### ISSUE TITLE
How can I use this repository??

### ISSUE THREAD

**Issue by jsrimr** [gusdnd852/Chatbot#1]
![image](https://user-images.githubusercontent.com/16870927/60104545-a7f42b00-979c-11e9-88b1-4a449e978098.png)

Program says it's not yet ready to answer..

**Comment by gusdnd852** [comment]
currently, all training data is korean. so, AI only can understand korean. if you want to use for another language, you should make your own training data, and train using your data.

**Comment by gusdnd852** [comment]
흠.. 한국분이신것 같은데...ㅋㅋㅋ

Currently all the example datasets are in Korean, and the example model has only learned Korean data, so it does not work well in other languages.

An example of a dialogue script in English is translated into English to inform foreigners that these models work well. The current model only works in Korean, and if you want to use a different language, you have to prepare and re-learn the training data set yourself.

I have written down how to use the new dataset in each part. Please note that. (If you want to use a different language than Korean, you have to implement the API part yourself)
