### ISSUE TITLE
src/entity/restaurant/train_entity.csv 파일이 깨진 듯 합니다.

### ISSUE THREAD

**Issue by paul-hyun** [gusdnd852/chatbot#3]
안녕하세요. 공유해주신 챗봇 소스를 공부하고 있습니다.
트레이닝 중 오류가 있는듯 해서 이슈 전달 드립니다.

src/entity/restaurant/train_entity.csv 파일이  깨진듯 합니다.
브라우저에서도 보이지 않고, 다운받아도 보이지 않네요.
파일 공유 부탁 드립니다.
감사합니다.

**Comment by gusdnd852** [comment]
현재 코드 업데이트 중입니다. 조만갑 업데이트하고 데이터까지 업로드 하겠습니다 ㅎㅎ.
